foreground #c2c2c5
background #0b0b19
cursor #c2c2c5

active_tab_foreground #0b0b19
active_tab_background #c2c2c5
inactive_tab_foreground #c2c2c5
inactive_tab_background #0b0b19

active_border_color #c2c2c5
inactive_border_color #0b0b19
bell_border_color #615d5a

color0 #0b0b19
color1 #615d5a
color2 #837c74
color3 #93857e
color4 #9c8c8c
color5 #a2948b
color6 #ac948c
color7 #c2c2c5
color8 #5a5a6e
color9 #615d5a
color10 #837c74
color11 #93857e
color12 #9c8c8c
color13 #a2948b
color14 #ac948c
color15 #c2c2c5
