foreground            #e8e4d8
background            #000000
cursor                #e8e4d8
selection_foreground  #000000
selection_background  #1e1e1e
color0  #121212
color8  #57544a
color1  #cf6679
color9  #8b3a3a
color2  #ded9c9
color10 #ded9c9
color3  #c9c3b0
color11 #c9c3b0
color4  #d4cfc0
color12 #d4cfc0
color5  #1e1e1e
color13 #1e1e1e
color6  #c9c3b0
color14 #c9c3b0
color7  #e8e4d8
color15 #a09f98
