foreground            #dfe3e7
background            #0f1417
cursor                #dfe3e7

selection_foreground  #d0e6f2
selection_background  #354a54

color0  #303538
color8  #8a9297

color1  #ffb4ab
color9  #ffb4ab

color2  #8bd0f0
color10 #8bd0f0

color3  #c6c2ea
color11 #c6c2ea

color4  #b4cad6
color12 #b4cad6

color5  #8bd0f0
color13 #8bd0f0

color6  #b4cad6
color14 #b4cad6

color7  #dfe3e7
color15 #c0c8cd
