foreground            #d3c6aa
background            #2d353b
cursor                #d3c6aa
selection_foreground  #d3c6aa
selection_background  #3d484d
color0  #475258
color8  #7a8478
color1  #e67e80
color9  #4c3743
color2  #a7c080
color10 #a7c080
color3  #7fbbb3
color11 #7fbbb3
color4  #83c092
color12 #83c092
color5  #3d484d
color13 #3d484d
color6  #7fbbb3
color14 #7fbbb3
color7  #d3c6aa
color15 #859289
