foreground            #e0e0e0
background            #121212
cursor                #e0e0e0
selection_foreground  #e0e0e0
selection_background  #2c2c2c
color0  #383838
color8  #6e6e6e
color1  #cf6679
color9  #4a1420
color2  #bb86fc
color10 #bb86fc
color3  #ffb74d
color11 #ffb74d
color4  #03dac6
color12 #03dac6
color5  #2c2c2c
color13 #2c2c2c
color6  #ffb74d
color14 #ffb74d
color7  #e0e0e0
color15 #a0a0a0
