foreground            #d4d4d4
background            #181818
cursor                #d4d4d4
selection_foreground  #d4d4d4
selection_background  #363636
color0  #2b2b2b
color8  #4a4a4a
color1  #8c4343
color9  #b55454
color2  #5c5c5c
color10 #5c5c5c
color3  #4a4a4a
color11 #4a4a4a
color4  #3d3d3d
color12 #3d3d3d
color5  #363636
color13 #363636
color6  #4a4a4a
color14 #4a4a4a
color7  #d4d4d4
color15 #a0a0a0
