foreground            #f1dfda
background            #1a110f
cursor                #f1dfda

selection_foreground  #ffdbd1
selection_background  #5d4037

color0  #3d322f
color8  #a08c87

color1  #ffb4ab
color9  #ffb4ab

color2  #ffb5a0
color10 #ffb5a0

color3  #d9c58d
color11 #d9c58d

color4  #e7bdb2
color12 #e7bdb2

color5  #ffb5a0
color13 #ffb5a0

color6  #e7bdb2
color14 #e7bdb2

color7  #f1dfda
color15 #d8c2bc
