foreground            #f0dee0
background            #191112
cursor                #f0dee0

selection_foreground  #ffd9de
selection_background  #5c3f44

color0  #3c3234
color8  #9f8c8e

color1  #ffb4ab
color9  #ffb4ab

color2  #ffb2bf
color10 #ffb2bf

color3  #ebbe90
color11 #ebbe90

color4  #e4bdc2
color12 #e4bdc2

color5  #ffb2bf
color13 #ffb2bf

color6  #e4bdc2
color14 #e4bdc2

color7  #f0dee0
color15 #d6c2c4
