# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃      ZUSQII  -  K I T T Y  C O L O R S  (matugen generated)      ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

background            #18130b
foreground            #ede1d4

cursor                #f2be6e
cursor_text_color     #442c00

selection_background  #55442a
selection_foreground  #f9dfbb

url_color             #b6cea3

# Black
color0   #241f17
color8   #2f2921

# Red
color1   #ffb4ab
color9   #93000a

# Green
color2   #b6cea3
color10  #384c2b

# Yellow
color3   #dcc3a1
color11  #55442a

# Blue
color4   #f2be6e
color12  #614000

# Magenta
color5   #d2eabd
color13  #d2eabd

# Cyan
color6   #7e570e
color14  #ffddaf

# White
color7   #d2c4b4
color15  #ede1d4

# Tabs
active_tab_background   #614000
active_tab_foreground   #ffddaf
inactive_tab_background #241f17
inactive_tab_foreground #d2c4b4
tab_bar_background      #18130b
