foreground            #eee0d5
background            #18120c
cursor                #eee0d5

selection_foreground  #fdddbd
selection_background  #58432c

color0  #3b332c
color8  #9d8e81

color1  #ffb4ab
color9  #ffb4ab

color2  #faba73
color10 #faba73

color3  #bdcc9c
color11 #bdcc9c

color4  #e0c1a3
color12 #e0c1a3

color5  #faba73
color13 #faba73

color6  #e0c1a3
color14 #e0c1a3

color7  #eee0d5
color15 #d4c4b5
