foreground            #c0caf5
background            #1a1b26
cursor                #c0caf5
selection_foreground  #c0caf5
selection_background  #292e42
color0  #3b4261
color8  #565f89
color1  #f7768e
color9  #db4b4b
color2  #7aa2f7
color10 #7aa2f7
color3  #73daca
color11 #73daca
color4  #9d7cd8
color12 #9d7cd8
color5  #292e42
color13 #292e42
color6  #73daca
color14 #73daca
color7  #c0caf5
color15 #a9b1d6
