foreground            #e2e2e9
background            #111318
cursor                #e2e2e9

selection_foreground  #dae2f9
selection_background  #3f4759

color0  #33353a
color8  #8e9099

color1  #ffb4ab
color9  #ffb4ab

color2  #acc7ff
color10 #acc7ff

color3  #ddbce0
color11 #ddbce0

color4  #bec6dc
color12 #bec6dc

color5  #acc7ff
color13 #acc7ff

color6  #bec6dc
color14 #bec6dc

color7  #e2e2e9
color15 #c4c6d0
