foreground            #efdfd6
background            #19120c
cursor                #efdfd6

selection_foreground  #ffdcc3
selection_background  #5a422e

color0  #3c332d
color8  #9e8d82

color1  #ffb4ab
color9  #ffb4ab

color2  #ffb77e
color10 #ffb77e

color3  #c5cb96
color11 #c5cb96

color4  #e3c0a6
color12 #e3c0a6

color5  #ffb77e
color13 #ffb77e

color6  #e3c0a6
color14 #e3c0a6

color7  #efdfd6
color15 #d6c3b7
