foreground            #f0dfd6
background            #19120d
cursor                #f0dfd6

selection_foreground  #ffdcc5
selection_background  #5b412f

color0  #3c332d
color8  #9f8d83

color1  #ffb4ab
color9  #ffb4ab

color2  #ffb782
color10 #ffb782

color3  #c7ca95
color11 #c7ca95

color4  #e4bfa7
color12 #e4bfa7

color5  #ffb782
color13 #ffb782

color6  #e4bfa7
color14 #e4bfa7

color7  #f0dfd6
color15 #d6c3b7
